layout_spectrum: 0.4269603
color:
  saturation: 0.6664876
  lightness: 0.4914071
  brandStrength: 0.4957035
  brandColors:
    - '#82A6C1'
    - '#577482'
    - '#FFFFFF'
    - '#FAE5B2'
    - '#CBD7DD'
  rhythmicContrast: 0.6074114
typography_spectrum: 0.4366273
name: Cross Connections
