name: Cross Connections
favicon: null
layout_spectrum: 0.75399
typography_spectrum: 0.4366273
title: Brendan Beale- wrecked and remade by Jesus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdcec0'
    - '#7f5e59'
    - '#363748'
    - '#ffffff'
    - '#a2a6a2'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
