name: Brendan Beale
favicon: null
layout_spectrum: 0.64487
typography_spectrum: 0.4366273
title: Wrecked and Remade by Jesus
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#81a4c0'
    - '#557582'
    - '#fae4b0'
    - '#feffff'
    - '#d4d6c2'
  brandStrength: 0.0625
  lightness: 0.5912997
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
