name: Brendan Beale
favicon: null
layout_spectrum: 0.75399
typography_spectrum: 0.4366273
title: Wrecked and Remade by Jesus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fce8cd'
    - '#82a5c1'
    - '#d27669'
    - '#fffc03'
    - '#c6070c'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
