name: Brendan Beale
favicon: null
layout_spectrum: 0.64487
typography_spectrum: 0.4366273
title: Wrecked and Remade by Jesus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#81a4c0'
    - '#557582'
    - '#fae4b0'
    - '#feffff'
    - '#d4d6c2'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
