name: Cross Connections
favicon: null
layout_spectrum: 0.72992
typography_spectrum: 0.4366273
title: Cross Connections
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d0171c'
    - '#e8bf89'
    - '#558724'
    - '#d17e14'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
