name: Cross Connections
favicon: null
layout_spectrum: 0.4269603
typography_spectrum: 0.4366273
title: Cross Connections
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#82a6c1'
    - '#577482'
    - '#ffffff'
    - '#fae5b2'
    - '#b3c2c9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
