title: Wrecked and Remade by Jesus
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0.375
  lightness: 0.5912997
  brandColors:
    - '#81a4c0'
    - '#557582'
    - '#fae4b0'
    - '#feffff'
    - '#d4d6c2'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Brendan Beale
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4366273
layout_spectrum: 0.64487
